describe('Cypress Test',() => {
  it ('None-existent login test',() => {
    cy.fixture('cypressTest').then(data => {
      cy.log('Переxод на страницу авторизации')
      cy.viewport(1750, 890)
      cy.visit(data.main_url)
      cy.log('Ввод несуществующего логина')
      cy.get('input[class="form-input--text form-input"]')
          .type(data.login)
      cy.log('Ввод несуществующего пароля')
      cy.get('input[class="form-input--password form-input"]')
          .type(data.password)
      cy.log('Клик по кнопке "Войти')
      cy.get('div[class="login-form__button"] button[type="submit"]')
          .click()
      cy.wait(1500)
      cy.log('Сбрось роли пользователя')
      cy.log('Переxод на страницу авторизации')
      cy.get('.page-nav__role-block > .button')
          .click()
      cy.wait(1500)
      cy.log('кликаем на выбор роли')

      cy.get('.select-role-form > :nth-child(1)')
          .click()
      cy.log('Выбираем что мы являемся какой то организации')
      cy.get('.variants-company > :nth-child(2)')
          .click()
      cy.log('Выбор')
      cy.get(':nth-child(1) > .form-control--medium > .form-input--text')
          .type(data.organization_company)
      cy.log('Название организации')
      cy.get(':nth-child(2) > .form-control--medium > .form-input--text')
          .type(data.address_company)
      cy.log('Название Адрес')
      cy.get('.form-area')
          .type(data.speciality)
      cy.log('Описание')
      cy.get('.create-company-form__description-block > .button')
          .click()
      cy.log('Подтверждение')
    })
  })
})